version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - /home/ubuntu/volume/data/db:/data/db
    
  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
      - bitcoind
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    volumes:
        - ./bitcore.config.json:/usr/src/app/bitcore.config.json
    env_file: .env

  bitcoind:
      image: kylemanna/bitcoind
      container_name: bitcoind
      ports:
          - 127.0.0.1:20008:20008
          - 127.0.0.1:20009:20009
      volumes:
          - /home/ubuntu/volume/bitcoin:/bitcoin
          - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

#insight:
  #image: insight
  #links:
    #- bitcore-node
  #environment:
    #- API_URL=bitcore-node
